### ISSUE TITLE
No guide for how to configure output for graylog-cli

### ISSUE THREAD

**Issue by ghost** [graylog-labs/cli-dashboard#11]
There is no guide or reference that I can find for how to setup the output stream for graylog-cli. The example in README.md shows http://serveraddress:port but then in the output configuration on the graylog server it shows the selectable protocols as TCP/TCP+TLS/UDP.

Does anyone know how to configure the outputs?

**Comment by joschi** [comment]
@clamport You don't need to create an output in Graylog to use this project. Simply create a valid user and a valid stream in Graylog (see http://docs.graylog.org/en/1.3/pages/getting_started/stream_alerts.html#create-a-stream) and follow the instructions in the `README.md` file of this project: https://github.com/Graylog2/cli-dashboard#installation
