### ISSUE TITLE
Could not get stream throughput

### ISSUE THREAD

**Issue by ghost** [graylog-labs/cli-dashboard#12]
I can now see the logs coming through, but I get a repeating message saying "Could not get stream throughput. Error: HTTP 404". Given enough time, this will start to overrun the log window portion.

**Comment by joschi** [comment]
@clamport Thanks for reporting this!

The cli-dashboard hasn't been updated (yet?) for more recent versions of Graylog which are handling the stream metrics (like throughput) differently.

**Comment by ghost** [comment]
Ah, ok. Does this mean the web-dashboard most likely won't work either?

**Comment by joschi** [comment]
@clamport To be honest, I don't know. Just try it and give us feedback if you hit some problems. :smile:

**Comment by leocwolter** [comment]
Hey @joschi, should it work if I clone and build the repo myself?

**Comment by joschi** [comment]
@leocwolter Sure, if you make the required changes. Make sure to open a pull request if you do so.

**Comment by fabiojvalente** [comment]
For the ones interested I've forked and committed a fix in https://github.com/fabiojvalente/cli-dashboard

**This breaks compatibility with previous API Versions.**

@joschi given that it is a "Lazy/Not so good" fix, I have decided not to request a merge

**Comment by joschi** [comment]
@fabiojvalente I think your fix is perfectly fine. Do you want to create a pull request for that?

**Comment by ghost** [comment]
Hi folks,

I'm getting this error with the lastest package as well. Any hints?

**Comment by estheban** [comment]
Hi, I get the error too.

**Comment by 0x4D31** [comment]
Same here
