### ISSUE TITLE
https

### ISSUE THREAD

**Issue by tonikarhu** [graylog-labs/cli-dashboard#13]
Is it possible to use https , seems like it doesnt work

**Comment by joschi** [comment]
@tonikarhu What problems do you have when using HTTPS?

**Comment by tonikarhu** [comment]
Hi this is the message im getting:

Could not get messages of stream. Error: Error: self signed certificate in
certificate chain
Could not get total throughput. Error: Error: self signed certificate in
certificate chain
Could not get stream throughput. Error: Error: self signed certificate in
certificate chain
Could not get alerts of stream. Error: Error: self signed certificate in
certificate chain
Could not get stream throughput. Error: Error: self signed certificate in
certificate chain
Could not get messages of stream. Error: Error: self signed certificate in
certificate chain
......
....

On 9 May 2016 at 13:29, Jochen Schalanda notifications@github.com wrote:

> @tonikarhu https://github.com/tonikarhu What problems do you have when
> using HTTPS?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Graylog2/cli-dashboard/issues/13#issuecomment-217829857

## 

---

Toni Karhu
Suezinkatu 7 A11
Helsinki 00220
Finland

Contact:
Mobile: 00 358 (0) 44 5000396
email: tonikarhu@gmail.com

**Comment by joschi** [comment]
@tonikarhu That's an error message from npm. Please refer to https://github.com/npm/npm/wiki/Troubleshooting#ssl-error for information how to solve this (or use a proper X.509 certificate in your Graylog setup).
