### ISSUE TITLE
graylog2 2.0.2

### ISSUE THREAD

**Issue by brumle80** [graylog-labs/cli-dashboard#14]
any chance this will be fixed so it works with latest graylog, was nice having it running in a terminal window on part of a second screen...

**Comment by edmundoa** [comment]
Which particular problems are you experiencing with it?

**Comment by matthanley** [comment]
Suspect this is a dup of #12, which I'm also experiencing.

**Comment by brumle80** [comment]
Yes it is, sorry for the duplication, I see there's a fix I can test.
8. jun. 2016 3:07 p.m. skrev "Matt Hanley" notifications@github.com:

**Comment by edmundoa** [comment]
Good to hear! In that case this was fixed in #15.
