### ISSUE TITLE
Could not get stream throughput. Error: HTTP 404

### ISSUE THREAD

**Issue by irom77** [graylog-labs/cli-dashboard#16]
It works for me but screen is trashed by 'Could not get stream throughput. Error: HTTP 404' messages coming down from top left corner ?

**Comment by edmundoa** [comment]
This is duplicated from https://github.com/Graylog2/cli-dashboard/issues/12, and the issue will be fixed once 0.14 is released in npm. You could also use the source directly, if you can't wait.
