### ISSUE TITLE
Alternatives for storing the passwords

### ISSUE THREAD

**Issue by xavierhardy** [graylog-labs/cli-dashboard#17]
Storing the password in a file is not secure at all. It would be better to have a prompt on startup (add an option for that) or to use Linux keyring.

On the other hand, the host and the default stream values could also be stored in the configuration file.

**Comment by STRML** [comment]
`v1.0.0` is out with some [significant changes](https://github.com/Graylog2/cli-dashboard/blob/master/CHANGELOG.md), including the ability to input your password via a cli opt or via prompt.

**Comment by xavierhardy** [comment]
I haven't used it in while due to the other bugs I mentioned. I'll try it, thanks.

**Comment by xavierhardy** [comment]
When I just give my username using `--username`, I do not get any password prompt, just a 401 error (Unauthorized).

**Comment by xavierhardy** [comment]
OK, it works, thanks a lot.
