### ISSUE TITLE
Update npm version to latest release

### ISSUE THREAD

**Issue by SBerkovic** [graylog-labs/cli-dashboard#19]
NPM is still on version 0.13.0
can we get it updated to 0.14.0 ?
https://www.npmjs.com/package/graylog-cli-dashboard

**Comment by edmundoa** [comment]
Hi @SBerkovic, we have some permission problems, but we should release the next version in npm soon. Sorry about that!

**Comment by SBerkovic** [comment]
@edmundoa  Thanks, I hope you guys figure it out soon,

**Comment by SBerkovic** [comment]
@edmundoa in order to get latest version I ended up installing straight from github using 
`npm install -g git+https://github.com/Graylog2/cli-dashboard.git`

**Comment by edmundoa** [comment]
That works too, thank you for posting the workaround here 😄
Sorry that is taking so long, we are currently busy getting Graylog 2.1.0 ready.

**Comment by STRML** [comment]
`v1.0.0` is out with some [significant changes](https://github.com/Graylog2/cli-dashboard/blob/master/CHANGELOG.md).
