### ISSUE TITLE
New version does not poll for stream throughput with new API

### ISSUE THREAD

**Issue by ryancmoon** [graylog-labs/cli-dashboard#21]
Starting graylog-dashboard results in 404's to http://:API_PATH/streams/:stream_id/throughput, which is 404. This needs to be updated to the current stream throughput path, which I cannot find the Graylog API Docs (nor can I find the entry in the Graylog REST API codebase to update it myself). It looks like it should be here: https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java , around line 264, but it is not listed.

14:41:23.879477 IP a.b.c.d.48310 > graylog-api-server.9601: Flags [P.], seq 1:136, ack 1, win 229, options [nop,nop,TS val 351730439 ecr 68026481], length 135
E.....@.@..(.......<..%...'....x...........
.......qGET /api/streams/580524244345491d9a3508cc/throughput HTTP/1.1
host: graylog-api-server:9601
accept: application/json
Connection: close

14:41:23.880730 IP graylog-api-server.9601 > a.b.c.d.48310: Flags [P.], seq 1:265, ack 136, win 235, options [nop,nop,TS val 68026481 ecr 351730439], length 264
E..<.
@.@......<....%......x..(q...."......
...q....HTTP/1.1 404 Not Found
X-Graylog-Node-ID: 4da9e014-b444-4a33-8b03-d797eeadfa4b
Vary: Accept-Encoding
Content-Type: application/json
Date: Mon, 17 Oct 2016 19:41:53 GMT
Connection: close
Content-Length: 50

**Comment by rayjohnson** [comment]
This tool is totally broken due to this issue.  UI just gets flooded with these 404 errors!  Will this be fixed please?

**Comment by wccropper** [comment]
Just starting out with graylog and checking out this tool and can confirm this error. Looking forward to a quick fix to be able to use the tool.

**Comment by joschi** [comment]
This project is deprecated. If one of you is interested in taking over maintenance, please contact us at hello@graylog.com.

**Comment by STRML** [comment]
This is not actually an issue with the module: the issue is with the REST API endpoint you're using.

See https://www.graylog.org/blog/8-tips-tricks-2-using-the-graylog-rest-api

If your graylog server is, say, `https://graylog.internal.mydomain.com`, set your host to `https://graylog.internal.mydomain.com:12900` to get the REST API.

**Comment by ryancmoon** [comment]
I moved my API to 9601, as referenced in the original submission.  If I hit /system/throughput, the API works fine. The API has been changed and this project has been removed.

**Comment by STRML** [comment]
My apologies, what you pasted was very difficult to read.

Then I can't replicate this - I have no issues running either the original code with a fixed `--host`, or [my fork](https://github.com/strml/cli-dashboard).
