### ISSUE TITLE
Publish latest version on npmjs

### ISSUE THREAD

**Issue by tholu** [graylog-labs/cli-dashboard#31]
The latest release 1.1.1 is not installable via npm yet (still on 1.0.0):
https://www.npmjs.com/package/graylog-cli-dashboard
Thanks!

**Comment by tholu** [comment]
Workaround meanwhile: 
```shell
npm install -g https://github.com/graylog-labs/cli-dashboard
```

**Comment by tholu** [comment]
@STRML That this issue is still open after almost three weeks this makes this project look rather abandoned. We really want to use this (and graylog), but we are not sure if creating Pull Requests makes sense, if the new versions are not regularly published.

**Comment by STRML** [comment]
@tholu We all have many, many demands on our time. This dashboard is intended to be used directly from the CLI, so just clone it and use. Free software is free software, no refunds.

I'll publish when I can.

**Comment by STRML** [comment]
`1.1.1` on npm.

**Comment by tholu** [comment]
@STRML Thank you! I didn't want to come across rude, I just wanted to know if there is an active interest in maintaining this official project from your side and I'd rather collaborate than work on the issues alone on a fork. Will try to fix some of the open issues.
